#BF528_Project_2_Biologist 
#Rachel Thomas

#clear all variables & start fresh
rm(list=ls(all.names=TRUE))

#load in libraries 
library(dplyr)
library(ggplot2)
library(tidyr)
library(RColorBrewer)


#Load and read data from SCC -- files generated by programmer 
fpkm_0 <- read.table('/projectnb/bf528/users/swiss_cheese2/project_2/P0_1_cufflinks/genes.fpkm_tracking', header = TRUE)
fpkm_0 <- fpkm_0  %>%  select(FPKM, tracking_id, gene_short_name)
#changed column name from FPKM to P0_1
colnames(fpkm_0) = gsub("FPKM", "P0_1", colnames(fpkm_0))
#relocate P0_1 column to last column 
fpkm_0 <- fpkm_0 %>% relocate(P0_1, .after = gene_short_name)


#load fpkm csv pre-generated sample file from SCC 
fpkm_matrix <- read.csv('/project/bf528/project_2/data/fpkm_matrix.csv', sep =  "\t")
#removes the "FPKM" from each header column
colnames(fpkm_matrix) = gsub("_FPKM", "", colnames(fpkm_matrix))
#combine fpkm p0_1 into fpkm matrix 
fpkm_combined <- merge(fpkm_0, fpkm_matrix)
fpkm_combined <- fpkm_combined %>% relocate(P0_1, .after = Ad_2)
fpkm_combined

#create new matrix for Line plot 1
fpkm_1 <- fpkm_combined %>% select(gene_short_name, P0_1, P4_1, P7_1, Ad_1)
fpkm_2 <- fpkm_combined %>% select(gene_short_name, P0_2, P4_2, P7_2, Ad_2)

#7.1 Line plots of Sarcomere 
gene_names = c('Csrp3', 'Tcap', 'Cryab', 'Pdlim5', 'Pygm', 'Myoz2', 'Des')

f <- fpkm_1[fpkm_1$gene_short_name %in% gene_names, ]
e <- f[-1]


row.names(e) <- f$gene_short_name
e <- as.data.frame(t(e))
e$Samples <- row.names(e)
row.names(e) <- NULL 
line_plot <- e %>%
  mutate(Samples = factor(Samples, levels = unique(Samples))) %>%
  gather(Genes, FPKM, -Samples) %>% 
  ggplot(aes(Samples, FPKM)) + 
  geom_line(aes(color = Genes, group = Genes)) +
  geom_point() +
  scale_y_log10() + 
  ggtitle("Sarcomere") +
  scale_color_brewer(palette = "Set1")  +
  theme_bw() + 
  theme(panel.grid = element_blank()) +
  theme(plot.title = element_text(hjust = 0.5))
png("sarcomere_line_plot.png")
line_plot
dev.off()



#7.1 Mitochondria plot 
gene_names_2 = c('Mpc1', 'Prdx3', 'Acat1', 'Echs1', 'Slc25a11', 'Phyh')

h <- fpkm_2[fpkm_2$gene_short_name %in% gene_names_2, ]
g <- h[-1]


row.names(g) <- h$gene_short_name
g <- as.data.frame(t(g))
g$Samples <- row.names(g)
row.names(g) <- NULL 
line_plot <- g %>%
  mutate(Samples = factor(Samples, levels = unique(Samples))) %>%
  gather(Genes, FPKM, -Samples) %>% 
  ggplot(aes(Samples, FPKM)) + 
  geom_line(aes(color = Genes, group = Genes)) +
  geom_point() +
  scale_y_log10() + 
  ggtitle("Mitochondria") +
  scale_color_brewer(palette = "Set1")  +
  theme_bw() + 
  theme(panel.grid = element_blank()) +
  theme(plot.title = element_text(hjust = 0.5))
png("Mitochondria_line_plot.png")
line_plot
dev.off()




#7.1 Cell Cycle  plot 
gene_names_3 = c('Cdc7', 'Cdk7', 'Cdc26', 'Bora', 'Cdc27', 'Cdc23','Cdc45', 'Aurkb', 'Rad51')

i <- fpkm_1[fpkm_1$gene_short_name %in% gene_names_3, ]
j <- i[-1]


row.names(j) <- i$gene_short_name
j <- as.data.frame(t(j))
j$Samples <- row.names(j)
row.names(j) <- NULL 
line_plot <- j %>%
  mutate(Samples = factor(Samples, levels = unique(Samples))) %>%
  gather(Genes, FPKM, -Samples) %>% 
  ggplot(aes(Samples, FPKM)) + 
  geom_line(aes(color = Genes, group = Genes)) +
  geom_point() +
  scale_y_log10() + 
  ggtitle("Cell Cycle") +
  scale_color_brewer(palette = "Dark2")  +
  theme_bw() + 
  theme(panel.grid = element_blank()) +
  theme(plot.title = element_text(hjust = 0.5))
png("CellCycle_line_plot.png")
line_plot
dev.off()

